### ISSUE TITLE
Flag tweets with mentions of drug names

### ISSUE THREAD

**Issue by Bcromas** [Bcromas/Pokee#3]

**Comment by nehabhomia** [comment]
potentially using these 2 APIs as sources:
1. https://mor.nlm.nih.gov/download/rxnav/RxNormAPIs.html#uLink=RxNorm_SOAP_getDrugs
2. https://open.fda.gov/apis/drug/

**Comment by Bcromas** [comment]
> potentially using these 2 APIs as sources:
> 
> 1. https://mor.nlm.nih.gov/download/rxnav/RxNormAPIs.html#uLink=RxNorm_SOAP_getDrugs
> 2. https://open.fda.gov/apis/drug/

These may be helpful but it looks like we still have to first identify the drug name in the tweet. I am thinking we could maintain a simple dict of drug names, simply split tweet body on whitespace, and check if any of the split words are in the dict.

**Comment by ganzelgr** [comment]
Since tweets may contain drug street-names, it may be helpful to scrape a website such as https://www.drugrehab.com/addiction/drugs/street-names-drugs/ and store those as well in the dictionary.

**Comment by Bcromas** [comment]
Closing this as I created a simple function that pulls in a list of drug names in a .csv and checks each word in a Tweet to see if it's in the drug list. Any additional enhancements should be tracked in a separate Issue.
