### ISSUE TITLE
Use Classifier Models for Task 1

### ISSUE THREAD

**Issue by nehabhomia** [Bcromas/Pokee#7]
split given training data into 80-20 and create pipelines for different classifier models.

**Comment by Bcromas** [comment]
I think we should work on this in a Jupyter NB similar to how we've completed 618 class exercises for classification (e.g. pull in data from whatever sources, store in a DataFrame, manipulate, build classification pipeline, etc.). 

What are your thoughts @nehabhomia @tengdann @ADM36 ?

**Comment by tengdann** [comment]
> I think we should work on this in a Jupyter NB similar to how we've completed 618 class exercises for classification (e.g. pull in data from whatever sources, store in a DataFrame, manipulate, build classification pipeline, etc.).
> 
> What are your thoughts @nehabhomia @tengdann @ADM36 ?

I agree with this; allows us to better visualize what is going on.

**Comment by ganzelgr** [comment]
I have pushed the code that I used for cleaning and tokenizing tweets to the repo. Feel free to use as much or as little of that code as you want to! It runs off of the 'task1_training_no_utf.tsv' file that I have pushed to the repo as well.
